In [26]:
import numpy as np
arr = np.zeros(20).reshape(4,5)
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
arr[2,3]=1
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [50]:
import numpy as np
arr = np.zeros(20).reshape(4,5)
trav = []

print("Shape",arr.shape)

def modifyAdd(r,c):
    arr[r][c] = 1
    if ((r,c)) not in trav:
        trav.append((r,c))

def right(r,c):
    modifyAdd(r,c)
    if c+1<len(arr[r]):
        if arr[r][c+1] == 0 :
            return right(r,c+1)
        else:
            return (r,c)
    else:
        return (r,c)
            
        
def down(r,c):
    modifyAdd(r,c)
    if r+1<len(arr):
        if arr[r+1][c] == 0:
            return down(r+1,c)
        else:
            return (r,c)
    else:
        return (r,c)
    
def left(r,c):
    modifyAdd(r,c)
    if c-1>=0:
        if arr[r][c-1] == 0:
            return left(r,c-1)
        else:
            return (r,c)
    else:
        return (r,c)
            
        
def up(r,c):
    modifyAdd(r,c)
    if r-1>=0:
        if arr[r-1][c] == 0:
            return up(r-1,c)
        else:
            return (r,c)
    else:
        return (r,c)
        
def clockwise(n,m):
    print("Clockwise")
    count = 0
    while count <= len(arr):
        n,m = right(n,m)
        n,m = down(n,m)
        n,m = left(n,m)
        n,m = up(n,m)
        count += 1
    return (n,m)

def anticlockwise(n,m):
    print("Anticlockwise")
    count = 0
    while count <= len(arr):
        n,m = down(n,m)
        n,m = right(n,m)
        n,m = up(n,m)
        n,m = left(n,m)
        count += 1
    return (n,m)
                    

print(arr)
# n,m = clockwise(3,4)
n,m = anticlockwise(3,4)
print("Travesing path",trav)
print(arr)
    
    

Shape (4, 5)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Anticlockwise
Travesing path [(3, 4), (2, 4), (1, 4), (0, 4), (0, 3), (0, 2), (0, 1), (0, 0), (1, 0), (2, 0), (3, 0), (3, 1), (3, 2), (3, 3), (2, 3), (1, 3), (1, 2), (1, 1), (2, 1), (2, 2)]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
