In [1]:
import numpy as np

In [6]:
arr = np.arange(1,10)
print(arr)
arr

[1 2 3 4 5 6 7 8 9]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr[arr>5]

array([6, 7, 8, 9])

In [9]:
arr%2==0

array([False,  True, False,  True, False,  True, False,  True, False])

In [10]:
arr[arr%2==0]

array([2, 4, 6, 8])

In [14]:
lst=list(range(1,10))
lst
print(lst)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [20]:
arr1 = np.array(lst)
arr1
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [22]:
arr1>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [23]:
arr1.shape

(9,)

In [24]:
arr1.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [25]:
arr1.size

9

In [26]:
arr1.dtype

dtype('int32')

In [27]:
arr1.itemsize

4

In [29]:
arr1.dtype.itemsize

4

In [30]:
arr1.data

In [31]:
arr1.strides

(4,)

In [32]:
arr1.ndim

1

In [37]:
print(arr1.base)

None


In [35]:
arr1.ndim

1

In [39]:
arr = np.arange(100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [42]:
arr1 = arr.reshape(10,10)
arr1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [44]:
arr2 = arr.reshape(5,20)
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [48]:
arr3 = arr.reshape(20,5)
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [56]:
zero = np.zeros((2,6)
zero

TypeError: Cannot interpret '6' as a data type

In [54]:
one = np.ones((5,3))
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [64]:
# student (id, name, branch)
# score (id, marks)
# tdf (id,name, marks)
import pandas as pd
df_student = pd.DataFrame({
    "id":[1,2,3],
    "name":['a','b','c'],
    "branch":['cs','mh','en'],
    "age":[10,20,30]
})
print(df_student)
df_score = pd.DataFrame({
    "id":[1,2,3],
    "marks":[10,20,30]
})
print(df_score)
tdf = df_student.merge(df_score,on='id')
print(tdf)
print()
print(df_student.loc[:,['name']])
print(tdf.loc[:,['id','name','marks']])
tdf["birthyear"]=2023-tdf["age"]
print(tdf)






   id name branch  age
0   1    a     cs   10
1   2    b     mh   20
2   3    c     en   30
   id  marks
0   1     10
1   2     20
2   3     30
   id name branch  age  marks
0   1    a     cs   10     10
1   2    b     mh   20     20
2   3    c     en   30     30

  name
0    a
1    b
2    c
   id name  marks
0   1    a     10
1   2    b     20
2   3    c     30
   id name branch  age  marks  birthyear
0   1    a     cs   10     10       2013
1   2    b     mh   20     20       2003
2   3    c     en   30     30       1993


In [65]:
tdf

id name branch  age  marks  birthyear
0   1    a     cs   10     10       2013
1   2    b     mh   20     20       2003
2   3    c     en   30     30       1993

In [62]:
tdf['birthyear'][2]=2010

C:\Users\kbhunia\AppData\Local\Temp\ipykernel_12072\522934436.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tdf['birthyear'][2]=2010


In [66]:
tdf.loc[1,'birthyear'] = 1990
tdf

id name branch  age  marks  birthyear
0   1    a     cs   10     10       2013
1   2    b     mh   20     20       1990
2   3    c     en   30     30       1993

In [72]:
tdf.loc[0,0]='new value'
tdf

id name branch   age  marks  birthyear          0
1  2.0    b     mh  20.0   20.0     1990.0        NaN
2  3.0    c     en  30.0   30.0     1993.0        NaN
0  NaN  NaN    NaN   NaN    NaN        NaN  new value

In [76]:
tdf.drop(columns = {0},inplace = True)
tdf

id name branch   age  marks  birthyear
1  2.0    b     mh  20.0   20.0     1990.0
2  3.0    c     en  30.0   30.0     1993.0