In [1]:
import numpy as np

In [4]:
first_ones_array = np.ones(6)
first_ones_array

array([1., 1., 1., 1., 1., 1.])

In [8]:
second_ones_array = np.ones((3,5))
second_ones_array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
third_ones_array = np.ones((3,5),dtype=int)
third_ones_array

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])